version: '3'
services:
  mse-app:
    container_name: mse-app-node
    volumes:
      - .:/app
    restart: always
    build:
      context: .
      tags:
        - "mse-nodeapp:1.2"
    ports:
      - '8480:3000'
    links:
      - mse-db
    networks:
      - mse-network
    environment:
      - MONGO_HOST=mse-db
  mse-db:
    container_name: mse-db-mongodb
    image: mongo:4.2.23
    restart: always
    volumes:
      - mse-db-data:/data/db
    networks:
      - mse-network
volumes:
  mse-db-data:
networks:
  mse-network: